theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  # - index.md
  - 2. probleemstelling.md
  - 3. doelstelling.md
  - 4. vraagstelling(en).md
  - 5. planning.md
  - 6. op te leveren producten \& kwaliteitseisen.md
  - 7. ontwikkelmethode.md
  - 8. projectorganisatie.md
  - 9. projectgrenzen.md
  - 10. Randvoorwaarden.md
  - 11. Risico's.md
